// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjvkVXsrxsd9W4-Ut4Ep89vG6uZWPA3ZU',
    appId: '1:816406914290:web:df55c82e48ed9a36d95c6b',
    messagingSenderId: '816406914290',
    projectId: 'aarogyamfin-56d93',
    authDomain: 'aarogyamfin-56d93.firebaseapp.com',
    storageBucket: 'aarogyamfin-56d93.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5nS4qjHejyuzcINYS9cdvJjKKDQA72Dw',
    appId: '1:816406914290:android:35ffe1aabc64a3d4d95c6b',
    messagingSenderId: '816406914290',
    projectId: 'aarogyamfin-56d93',
    storageBucket: 'aarogyamfin-56d93.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoQB5oqxBFcvs6oXWZ9QPE7ybFXN_SxfY',
    appId: '1:816406914290:ios:526139363848d6e1d95c6b',
    messagingSenderId: '816406914290',
    projectId: 'aarogyamfin-56d93',
    storageBucket: 'aarogyamfin-56d93.firebasestorage.app',
    iosBundleId: 'com.example.aarogyamfin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoQB5oqxBFcvs6oXWZ9QPE7ybFXN_SxfY',
    appId: '1:816406914290:ios:526139363848d6e1d95c6b',
    messagingSenderId: '816406914290',
    projectId: 'aarogyamfin-56d93',
    storageBucket: 'aarogyamfin-56d93.firebasestorage.app',
    iosBundleId: 'com.example.aarogyamfin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjvkVXsrxsd9W4-Ut4Ep89vG6uZWPA3ZU',
    appId: '1:816406914290:web:dbe387c8f8d3b1d2d95c6b',
    messagingSenderId: '816406914290',
    projectId: 'aarogyamfin-56d93',
    authDomain: 'aarogyamfin-56d93.firebaseapp.com',
    storageBucket: 'aarogyamfin-56d93.firebasestorage.app',
  );
}
